[project]
name = "game-of-life-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "numpy>=2.2.6",
    "pytest>=8.3.5",
    "scipy>=1.15.3",
    "uvicorn>=0.34.2",
    "websockets>=15.0.1",
]
